version: "3.9"
services:
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vundocker1512/givenshare:givenshare-ui
    environment:
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    ports:
      - 3000:3000
    container_name: givenshare-ui
    networks:
      - givenshare-stack-net
    #  volumes:
    #   -  ./ui/src:/usr/app/src
    #   -  ./ui/public:/usr/app/public
    depends_on:
      - api
    stdin_open: true
    tty: true

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vundocker1512/givenshare:givenshare-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOCAL_DATABASE_URL: ${LOCAL_DATABASE_URL}
      FE_URL: ${FE_URL}
      BE_URL: ${BE_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_BUCKET_REGION: ${AWS_BUCKET_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8000:8000
    container_name: givenshare-api
    networks:
      - givenshare-stack-net
    # volumes:
    #   - api_public:/usr/app/public

networks:
  givenshare-stack-net:
    driver: bridge
# volumes:
#   api_public:
#     driver: local
