const mongoose = require("mongoose");

const donateSchema = new mongoose.Schema({
  // _id is auto generated by MongoDB
  projectId: {
    type: String,
    required: true,
  },
  userId: {
    type: String, 
    required: true
  },
  amount: {
    type: Number, 
    default: 0,
  },
  timestamp: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model("Donate", donateSchema);