const mongoose = require("mongoose");

const { userSchema } = require("./users")

const projectSchema = new mongoose.Schema({
  // _id is auto generated by MongoDB
  title: {
    type: String,
    required: true,
  },
  subTitle: {
    type: String,
    // required: true
  },
  category: {
    type: [String],
    required: true,
  },
  endDate: {
    type: Date,
    required: true,
    default: Date.now,
  },
  currentProgress: {
    type: Number,
    required: true,
    default: 0,
  },
  backers: {
    type: Map,
    of: Number
  },
  author: userSchema,
  goal: {
    type: Number, 
    required: true,
  },
  description: {
    type: String,
    required: true,
    default: "No description",
  },
  coverURL: {
    type: String,
    required: true
  },
  visualMedias: {
    type: [String],
    required: false
  },
});

module.exports = mongoose.model("Project", projectSchema);
